# Generated by Django 5.0.6 on 2024-06-07 08:02

import django.db.models.deletion
import storeCategoryData.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("LabelCarftProjectSetup", "0007_alter_projectinvitation_token"),
        ("StoreLabelData", "0003_alter_label_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(upload_to=storeCategoryData.models.upload_to),
                ),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category_image",
                        to="LabelCarftProjectSetup.projectcategory",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_label_image",
                        to="StoreLabelData.image",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_image",
                        to="LabelCarftProjectSetup.project",
                    ),
                ),
            ],
        ),
    ]
