# Generated by Django 5.0.6 on 2024-07-03 09:21

import django.db.models.deletion
import storeCategoryData.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("LabelCarftProjectSetup", "0001_initial"),
        ("StoreLabelData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(upload_to=storeCategoryData.models.upload_to),
                ),
                ("image_width", models.FloatField(blank=True, default=640, null=True)),
                ("image_height", models.FloatField(blank=True, default=640, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category_images",
                        to="LabelCarftProjectSetup.projectcategory",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_label_images",
                        to="StoreLabelData.image",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_images",
                        to="LabelCarftProjectSetup.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_image_labels",
                        to="storeCategoryData.categoryimage",
                    ),
                ),
            ],
        ),
    ]
