# Generated by Django 5.0.6 on 2024-06-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeCategoryData", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryimage",
            name="image_height",
            field=models.FloatField(blank=True, default=640, null=True),
        ),
        migrations.AddField(
            model_name="categoryimage",
            name="image_width",
            field=models.FloatField(blank=True, default=640, null=True),
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="label",
            field=models.CharField(max_length=100),
        ),
    ]
