# Generated by Django 5.0.6 on 2024-09-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeCategoryData", "0002_categoryimage_uploaded_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryimage",
            name="image_file",
        ),
        migrations.AddField(
            model_name="categoryimage",
            name="firebase_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
