# Generated by Django 5.0.6 on 2024-06-11 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "storeCategoryData",
            "0002_categoryimage_image_height_categoryimage_image_width_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryimage",
            name="image_height",
        ),
        migrations.RemoveField(
            model_name="categoryimage",
            name="image_width",
        ),
    ]
