# Generated by Django 5.0.6 on 2024-06-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeCategoryData", "0003_remove_categoryimage_image_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryimage",
            name="image_height",
            field=models.FloatField(blank=True, default=640, null=True),
        ),
        migrations.AddField(
            model_name="categoryimage",
            name="image_width",
            field=models.FloatField(blank=True, default=640, null=True),
        ),
    ]
