# Generated by Django 4.2.16 on 2025-01-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeCategoryData', '0003_remove_categoryimage_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelabel',
            name='label_id',
            field=models.CharField(default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
