# Generated by Django 4.2.16 on 2025-01-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeCategoryData', '0004_imagelabel_label_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='label_id',
            field=models.CharField(max_length=100),
        ),
    ]
