# Generated by Django 5.0.6 on 2024-06-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0011_alter_projectinvitation_token"),
        ("StoreLabelData", "0003_alter_label_label"),
        (
            "storeCategoryData",
            "0004_categoryimage_image_height_categoryimage_image_width",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryimage",
            name="height",
        ),
        migrations.RemoveField(
            model_name="categoryimage",
            name="label",
        ),
        migrations.RemoveField(
            model_name="categoryimage",
            name="width",
        ),
        migrations.RemoveField(
            model_name="categoryimage",
            name="x",
        ),
        migrations.RemoveField(
            model_name="categoryimage",
            name="y",
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_images",
                to="LabelCarftProjectSetup.projectcategory",
            ),
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_label_images",
                to="StoreLabelData.image",
            ),
        ),
        migrations.AlterField(
            model_name="categoryimage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_images",
                to="LabelCarftProjectSetup.project",
            ),
        ),
        migrations.CreateModel(
            name="ImageLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="storeCategoryData.categoryimage",
                    ),
                ),
            ],
        ),
    ]
