# Generated by Django 5.0.6 on 2024-06-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeCategoryData", "0005_remove_categoryimage_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagelabel",
            name="category_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_image_labels",
                to="storeCategoryData.categoryimage",
            ),
        ),
    ]
