# Generated by Django 5.0.6 on 2024-06-11 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0014_alter_projectinvitation_token"),
        ("storeCategoryData", "0007_remove_categoryimage_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryimage",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_images",
                to="LabelCarftProjectSetup.project",
            ),
            preserve_default=False,
        ),
    ]
