# Generated by Django 5.0.6 on 2024-06-07 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("LabelCarftProjectSetup", "0005_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LabelCarftProjectSetup.project",
                    ),
                ),
            ],
        ),
    ]
