# Generated by Django 5.0.6 on 2024-09-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UploadDataSetLableCraft", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="originalimage",
            name="path",
        ),
        migrations.AddField(
            model_name="originalimage",
            name="firebase_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
