# Generated by Django 5.0.6 on 2024-08-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="MKhMsmSmN37wnDpXtNF8", max_length=50, unique=True
            ),
        ),
    ]
