# Generated by Django 5.0.6 on 2024-06-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="color",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="color",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="color",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="toxicity",
            name="color",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="wastetype",
            name="color",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="CS85wkrTyJQywcLg3Cuj", max_length=50, unique=True
            ),
        ),
    ]
