# Generated by Django 5.0.6 on 2024-09-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0002_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="bUuEOFFoQA710ya1Rwmm", max_length=50, unique=True
            ),
        ),
    ]
