# Generated by Django 5.0.6 on 2024-06-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "LabelCarftProjectSetup",
            "0002_condition_color_grade_color_material_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="UNDVLktnJjx1YpGeZg2E", max_length=50, unique=True
            ),
        ),
    ]
