# Generated by Django 5.0.6 on 2024-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0003_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="gg1F6Mc4oU5N83RzlNlR", max_length=50, unique=True
            ),
        ),
    ]
