# Generated by Django 5.0.6 on 2024-06-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0003_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="hW8moVAhIGiuLYTHQVAA", max_length=50, unique=True
            ),
        ),
    ]
