# Generated by Django 5.0.6 on 2024-05-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "LabelCarftProjectSetup",
            "0004_alter_project_dataset_alter_projectinvitation_token",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="J6PgLjW37ug0XzMk843n", max_length=50, unique=True
            ),
        ),
    ]
