# Generated by Django 5.0.6 on 2024-09-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0004_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="wwdV3es5VznaDsM2k4vJ", max_length=50, unique=True
            ),
        ),
    ]
