# Generated by Django 5.0.6 on 2024-06-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0004_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="g22vkGQm73geUeyEci20", max_length=50, unique=True
            ),
        ),
    ]
