# Generated by Django 5.0.6 on 2024-05-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0005_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="kNeyuV0RrTAhq0Djt2qG", max_length=50, unique=True
            ),
        ),
    ]
