# Generated by Django 4.2.16 on 2024-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabelCarftProjectSetup', '0005_alter_projectinvitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvitation',
            name='token',
            field=models.CharField(default='63l0PbC54gGgxd8HhAeJ', max_length=50, unique=True),
        ),
    ]
