# Generated by Django 4.2.16 on 2024-09-19 03:33

import LabelCarftProjectSetup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabelCarftProjectSetup', '0006_alter_projectinvitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvitation',
            name='token',
            field=models.CharField(default=LabelCarftProjectSetup.models.generate_unique_token, max_length=50, unique=True),
        ),
    ]
