# Generated by Django 5.0.6 on 2024-06-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0006_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="LMmBb7WY8q736pmDdCzC", max_length=50, unique=True
            ),
        ),
    ]
