# Generated by Django 5.0.6 on 2024-06-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0007_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="bzfqd6XiTkezie4ikVE9", max_length=50, unique=True
            ),
        ),
    ]
