# Generated by Django 5.0.6 on 2024-06-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0009_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="F9xeIoEvIR3ca4MzjI8H", max_length=50, unique=True
            ),
        ),
    ]
