# Generated by Django 5.0.6 on 2024-06-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0011_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="nR2h6ODOW9RHrcq7M4Bg", max_length=50, unique=True
            ),
        ),
    ]
