# Generated by Django 5.0.6 on 2024-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0016_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="o8ROwRxCzu7pMupX2Bl8", max_length=50, unique=True
            ),
        ),
    ]
