# Generated by Django 5.0.6 on 2024-06-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0017_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="lpgFn7xQ1UIQFqrWvcnt", max_length=50, unique=True
            ),
        ),
    ]
