# Generated by Django 5.0.6 on 2024-06-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0021_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="bQh1bnIyNzRj0fyp8ogr", max_length=50, unique=True
            ),
        ),
    ]
