# Generated by Django 5.0.6 on 2024-06-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0023_alter_projectinvitation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="token",
            field=models.CharField(
                default="FENgXJZHmRqCiu1dsvF5", max_length=50, unique=True
            ),
        ),
    ]
