# Generated by Django 5.0.6 on 2024-06-05 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCarftProjectSetup", "0003_alter_projectinvitation_token"),
        ("StoreLabelData", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="LabelCarftProjectSetup.projectcategory",
            ),
        ),
    ]
