# Generated by Django 5.0.6 on 2024-06-17 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreLabelData", "0001_initial"),
        ("UploadDataSetLableCraft", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="original_image",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OriginalImage",
                to="UploadDataSetLableCraft.originalimage",
            ),
            preserve_default=False,
        ),
    ]
