# Generated by Django 5.0.6 on 2024-05-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreLabelData", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
