# Generated by Django 5.0.6 on 2024-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreLabelData", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image_file",
        ),
        migrations.AddField(
            model_name="image",
            name="firebase_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
