# Generated by Django 5.0.6 on 2024-06-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreLabelData", "0002_image_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
