# Generated by Django 4.2.16 on 2024-10-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreLabelData', '0002_remove_image_image_file_image_firebase_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.FloatField(blank=True, default=540, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.FloatField(blank=True, default=540, null=True),
        ),
    ]
