# Generated by Django 5.0.6 on 2024-06-18 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StoreLabelData", "0002_image_original_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="status",
            field=models.CharField(
                choices=[
                    ("unlabeled", "Unlabeled"),
                    ("labeled", "Labeled"),
                    ("verified", "Verified"),
                ],
                default="unlabeled",
                max_length=20,
            ),
        ),
    ]
