# Generated by Django 4.2.16 on 2025-01-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreLabelData', '0003_image_image_height_image_image_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='label_id',
            field=models.CharField(default=12, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
