# Generated by Django 5.0.6 on 2024-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trackAssginImagesAnnoatation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="unassigned",
                max_length=20,
            ),
        ),
    ]
