# Generated by Django 5.0.6 on 2024-05-22 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LabelCraft", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectinvitation",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projectinvitation",
            name="registered_user",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectInvitation",
        ),
    ]
